# Generated by Django 3.2 on 2021-05-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
