# Generated by Django 3.2 on 2021-05-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_alter_announcement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
