# Generated by Django 3.2 on 2021-05-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0008_announcement_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
