# Generated by Django 3.2 on 2021-05-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0003_alter_status_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100, null=True)),
                ('ip_address', models.CharField(default=None, max_length=100)),
                ('state', models.CharField(default=None, max_length=100)),
                ('resource', models.CharField(default=None, max_length=100)),
                ('additional_info', models.CharField(default=None, max_length=500)),
                ('created_at', models.CharField(default=None, max_length=20)),
                ('status', models.ForeignKey(default='Not verified', on_delete=django.db.models.deletion.CASCADE, related_name='form_status', to='status.status')),
            ],
        ),
    ]
