# Generated by Django 3.2 on 2021-05-04 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource', '0001_initial'),
        ('state', '0001_initial'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100, null=True)),
                ('ip_address', models.CharField(default=None, max_length=100)),
                ('additional_info', models.CharField(default=None, max_length=500)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_resource', to='resource.resource')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_state', to='state.state')),
                ('status', models.ForeignKey(default='Not verified', on_delete=django.db.models.deletion.CASCADE, related_name='form_status', to='status.status')),
            ],
        ),
    ]
