# Generated by Django 3.2 on 2021-05-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='created_at',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
