# Generated by Django 3.2 on 2021-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20210505_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='form',
            name='resource',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='state',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
