# Generated by Django 3.2 on 2021-05-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=100, null=True)),
                ('description', models.CharField(default=None, max_length=1000)),
                ('ip_address', models.CharField(default=None, max_length=100)),
                ('created_at', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
